package Translator;

public enum TokenType {
    VAR, PRINT, WHILE, END,
    IDENTIFIER, NUMBER,
    PLUS, MINUS, MULTIPLY, DIVIDE,
    GREATER_THAN, LESS_THAN, EQUALS, ASSIGN,
    LEFT_PAREN, RIGHT_PAREN,
    WHITESPACE, EOF, UNKNOWN
}